config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[new create destroy] # в единственном числе, чтобы при DELETE не запрашивался id
  resources :users
  resources :goals, only: %i[new create destroy show] do
    resources :tasks, only: %i[create show destroy]
  end
  resources :handbooks, only: %i[index] 
  get '/departments', to: 'handbooks#departments_link', as: 'departments_link'
  get '/staff', to: 'handbooks#staff_link', as: 'staff_link'


  

  get '/my_documents', to: 'documents#my_documents', as: 'my_documents'

  #get "/routes/:id", to: 'routes#show', as: 'route'  
  get "/goals_inbox", to: 'goals#index_inbox', as: 'inbox_goals' 
  get "/goals_outbox", to: 'goals#index_outbox', as: 'outbox_goals' 

  resources :documents do
    resources :routes, only: %i[new create destroy show]
  end

  resources :routes, only: %i[new create destroy show] do
    resources :steps, only: %i[create show destroy]
  end 
  
  
   
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  root 'pages#index'
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    has_many :documents
    has_many :routes
    has_many :goals
    has_many :tasks, dependent: :destroy
    has_many :steps

    validates :login, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_authentication, only: %i[edit update show]
  before_action :set_user!, only: %i[edit update]
  def index
  end

  def new
      @user = User.new
  end
    
  def create
      @user = User.new user_params
       if @user.save
         sign_in @user
         flash[:success] = "Пользователь #{@user.login} зарегистрирован"
         redirect_to root_path
       else
         flash[:warning] = "Ошибка"
         render :new
       end
  end

  def show
    @department = Department.find_by id: @current_user.department_id
  end

  def edit
  end

  def update
    if @user.update user_profile_params
      flash[:success] = "Изменено!"
      redirect_to user_path(@current_user)
    else
      render :edit
    end
  end

    def user_params
        params.require(:user).permit(:login, :password, :password_confirmation, :role)
    end

    def set_user!
      @user = User.find params[:id]
    end

    def user_profile_params
      params.require(:user).permit(:surname, :name, :patronymic, :phone, :email, :post, :department_id)
    end

end

app/views/users/edit.html.erb
<%= link_to '« назад', user_path(@current_user), class: 'previous' %>
<h1>Редактирование профиля <%=@current_user.login%></h1>
</br>
<%= form_with model: @user do |f| %>
  <ol class="profile">
<div class="mb-2 row">
    <div class="col-sm-5"> <li id="surname">
      <%= f.text_field :surname, style: "border: none;", value: @current_user.surname %>
    </li></div>
</div>
<div class="mb-2 row">
    <div class="col-sm-5"> <li id="name">
      <%= f.text_field :name, style: "border: none;", value: @current_user.name %>
    </li></div>
    <div class="col-sm-5"> <li id="patronymic">
      <%= f.text_field :patronymic, style: "border: none;", value: @current_user.patronymic %>
    </li></div>
</div>
<div class="mb-2 row">
    <div class="col-sm-5"> <li id="phone">
      <%= f.text_field :phone, style: "border: none;", value: @current_user.phone %>
    </li></div>
    <div class="col-sm-5"> <li id="email">
      <%= f.text_field :email, style: "border: none;", value: @current_user.email %>
    </li></div>
</div>
<div class="mb-2 row">
    <div class="col-sm-5"> <li id="post">
      <%= f.text_field :post, style: "border: none;", value: @current_user.post %>
    </li></div>
    <div class="col-sm-5"> <li id="department">
      <%= f.text_field :department_id, list: 'dep', style: "border: none;" %>
      <datalist id="dep">
        <% Department.all.each do |dep| %>
          <option label="<%= dep.dep_name %>" value ="<%= dep.id %>"></option>
        <% end %>
      </datalist></li></div>
</div>
</ol>

<%= f.submit "Сохранить изменения", class: 'button' %>
<%end%>

app/views/users/index.html.erb
<li><%= link_to 'Регистрация', new_user_path, class: 'nav-link px-2' %></li>
<li><%= link_to 'Вход', new_session_path, class: 'nav-link px-2' %></li>

app/views/users/new.html.erb
<% provide :page_title, 'Registartion' %>

<h1>Регистрация</h1>
<%= form_with model: @user do |f| %>
<div class="signin">
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label 'Логин' %>
    </div>

    <div class="col-sm-4">
      <%= f.text_field :login, placeholder: 'Логин', class: 'form-control form-control-lg' %>
    </div>
  </div>

 <div class="mb-3 row">
    <div class="col-sm-3 col-form-label">
      <%= f.label :role, "Обычный пользователь", :value => "true"  %>
    <%= f.radio_button :role, 1 %>
        </div>
        <div class="col-sm-2 col-form-label">
    <%= f.label :role, "Администратор", :value => "false" %>
    <%= f.radio_button :role, 2 %>
    </div>
</div>


  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label 'Пароль' %>
    </div>

    <div class="col-sm-4">
      <%= f.password_field :password, class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label 'Подтверждение пароля' %>
    </div>

    <div class="col-sm-4">
      <%= f.password_field :password_confirmation, class: 'form-control form-control-lg' %>
    </div>
  </div>


  <%= f.submit (@user.new_record? ? "Зарегистрировать" : "Save"),
    class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/users/show.html.erb
  <div class="mb-3 row">
   <div class="col-sm-7 ">
<h1>Профиль пользователя <%=@current_user.login%>
</h1></div>
<div class="col-sm-3 ">
<%= link_to 'Выйти', session_path, data: {method: :delete}, class: 'shine-button' %>
</div>
</div>
<ol class="profile">
<div class="mb-2 row">
    <div class="col-sm-5"> <li id="surname"><%= @current_user.surname%></li> </div>
    <div class="col-sm-5"> <li id="role">
        <% if @current_user.role == 1%> Обычный пользователь <%end%>
        <% if @current_user.role == 2%> Администратор <%end%></li> 
    </div>
</div>
<div class="mb-2 row">
    <div class="col-sm-5"> <li id="name"><%= @current_user.name%></li> </div>
    <div class="col-sm-5"> <li id="patronymic"><%= @current_user.patronymic%></li> </div>
</div>
<div class="mb-2 row">
    <div class="col-sm-5"> <li id="phone"><%= @current_user.phone%></li> </div>
    <div class="col-sm-5"> <li id="email"><%= @current_user.email%></li> </div>
</div>
<div class="mb-2 row">
    <div class="col-sm-5"> <li id="post"><%= @current_user.post%></li> </div>
    <div class="col-sm-5"> <li id="department">
     <%unless @current_user.department_id.nil? %>
        <%= @department.dep_name %>
     <%else%>
        не указан
     <%end%></li> </div>
</div>
</ol>
<div class="mb-2 row">
 <div class="col-sm-5"> 
    <%= link_to '🖉 Изменить данные', edit_user_path(@current_user), style: 'color:#5C2018; font-size: 18px;'%>
 </div>
</div>  