config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[new create destroy] # в единственном числе, чтобы при DELETE не запрашивался id
  resources :users
  resources :goals, only: %i[new create destroy show] do
    resources :tasks, only: %i[create show destroy]
  end
  resources :handbooks, only: %i[index] 
  get '/departments', to: 'handbooks#departments_link', as: 'departments_link'
  get '/staff', to: 'handbooks#staff_link', as: 'staff_link'


  

  get '/my_documents', to: 'documents#my_documents', as: 'my_documents'

  #get "/routes/:id", to: 'routes#show', as: 'route'  
  get "/goals_inbox", to: 'goals#index_inbox', as: 'inbox_goals' 
  get "/goals_outbox", to: 'goals#index_outbox', as: 'outbox_goals' 

  resources :documents do
    resources :routes, only: %i[new create destroy show]
  end

  resources :routes, only: %i[new create destroy show] do
    resources :steps, only: %i[create show destroy]
  end 
  
  
   
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  root 'pages#index'
end

app/models/document.rb
class Document < ApplicationRecord
    belongs_to :user
    has_many :routes, dependent: :destroy
    #has_many :users, through: :routes
    has_one_attached :file     

    def self.search(search_number, search_name, search_type, search_contractor)
        if search_contractor == ""
            self.where("number LIKE ? and name LIKE ? and doc_type LIKE ?", "%#{search_number}%", "%#{search_name}%", "%#{search_type}%")
        else
            self.where("number LIKE ? and name LIKE ? and doc_type LIKE ? and contractor_id::text LIKE ?", "%#{search_number}%", "%#{search_name}%","%#{search_type}%", "%#{search_contractor}%")
        end
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
before_action :require_authentication
before_action :set_document!, only: %i[edit update show destroy]

  def index
    if params[:search_number] or params[:search_name] or params[:search_type] or params[:search_contractor]
      @documents = search
    else
      @documents = Document.all.order('created_at DESC')
    end
  end

  def search
    @documents = Document.search(params[:search_number], params[:search_name], params[:search_type], params[:search_contractor])
  end

  def my_documents
    @documents = @current_user.documents.all
    render 'documents/my_doc'
  end
  
  def new 
    @contractors = Contractor.all
    @document = Document.new
    dep = Department.find_by id: @current_user.department_id
    Document.all.empty? ? doc_count = 1 : doc_count = Document.last.id+1
    @reg_number = "#{doc_count}/#{dep.dep_code}"
  end

  def show
    @route = @document.routes.build
    @routes = Route.where document_id: @document.id
  end
  
  def create
    @document = @current_user.documents.build document_params
      if @document.save
        redirect_to document_path(@document)
      else
        flash[:warning] = "Ошибка!"
        redirect_to documents_path
      end
  end

  def edit
  end

  def update
    if @document.update document_params
      flash[:success] = "Изменено!"
      redirect_to documents_path
    else
      render :edit
    end
  end

  def destroy
    #@document.file.purge
    @document.destroy
    redirect_to documents_path
  end

  private
    def document_params
      params.require(:document).permit(:number, :name, :file, :doc_type, :contractor_id)
    end

    def set_document!
      @document = Document.find params[:id]
    end
end

app/views/documents/_doc_table.html.erb
<tr> <!--ряд с ячейками заголовков-->
    <th colspan="2">название</th>
    <th colspan="2">тип документа</th>
    <th></th>
  </tr> 
  <% @documents.each do |doc| %>
    <tr> <!--ряд с ячейками тела таблицы-->
     <td><%= doc.name%></td>
     <td></td>
     <td><%= doc.doc_type%></td>
     <td></td>
     <td><%=link_to "Посмотреть", document_path(doc),  style: 'color:#5C2018;' %></td>
    </tr>    
  <%end %>

app/views/documents/_menu.html.erb
<div class="widget-doc">
  <ul>
    <li><%= link_to 'Все документы', documents_path, class: 'a', style:('font-weight:bold;' if current_page?(documents_path)) %></li>
    <li><%= link_to 'Мои документы', my_documents_path, class: 'a', style:('font-weight:bold;' if current_page?(my_documents_path)) %></li>
    
    <li> <%=form_tag(documents_path, :method => "get", from: "search-form") do %>
    Номер документа<%= text_field_tag :search_number, params[:search_number], class:'form-control mb-2' %>
    Название документа<%= text_field_tag :search_name, params[:search_name], class:'form-control mb-2' %>
    Тип документа<%= text_field_tag :search_type, params[:search_type], class:'form-control mb-2' %> 
    Контрагент<%=select_tag :search_contractor, options_for_select(Hash[Contractor.all.map { |c| [c.contr_name, c.id]}].merge({"нет" => ""}), selected: params[:search_contractor]), class:'form-select mb-2'%> 
     <%= submit_tag "🔍 Найти", class: 'btn btn-light' %> <%end%></li>
  </ul>
</div>

app/views/documents/index.html.erb
<div class="row">
<div class="col-sm-3">
<%= link_to 'Создать документ', new_document_path, class: 'shine-button' %>
<%= render 'menu'%>
</div>
 <div class="col-sm-6">
  <table class="doc-table">
   <caption>
    Мои документы
   </caption>
  <tr> <!--ряд с ячейками заголовков-->
    <th colspan="2">название</th>
    <th colspan="2">тип документа</th>
    <th></th>
  </tr> 
  <% @documents.each do |doc| %>
    <tr> <!--ряд с ячейками тела таблицы-->
     <td><%= doc.name%></td>
     <td></td>
     <td><%= doc.doc_type%></td>
     <td></td>
     <td><%=link_to "Посмотреть", documents_path,  style: 'color:#5C2018;' %></td>
    </tr>    
  <%end %>
 </table>
</div>
</div>
 




  

app/views/documents/my_doc.html.erb
<div class="row">
<div class="col-sm-3">
<%= link_to 'Создать документ', new_document_path, class: 'shine-button' %>
<%= render 'menu'%>
</div>
 <div class="col-sm-6">
  <table class="doc-table">
   <caption>
    Мои документы
   </caption>
  <%= render 'doc_table'%>
 </table>
</div>
</div>
 




  

app/views/documents/new.html.erb
 <div class="row">
    <div class="col-auto">
      <%= link_to '« назад', documents_path, class: 'previous', style: 'margin-top:auto' %>
    </div>

<div class="col-lg-10">
<div class="decor">
  <div class="form-left-decoration"></div>
    <div class="form-right-decoration"></div>
      <div class="circle"></div>
        <div class="form-inner">

        <h3>Новый документ</h3>
        <%= form_with model: @document do |f| %>

        <%= f.label "Регистрационный номер" %>
        <%= f.text_field :number, readonly: true, class: 'form-control form-control-lg', value: @reg_number %>
  
        <%= f.label "Название документа" %>
        <%= f.text_field :name, placeholder: 'Название документа', class: 'form-control form-control-lg', style: 'focus:on' %>

        <%= f.label "Тип документа" %>
        <%= f.select :doc_type, ['Договор', 'Записка', 'Заявление', 'Приказ', 'Протокол'], placeholder: 'Выберите тип документа'%>

        <%= f.label "Контрагент" %>
        <%= f.select :contractor_id, options_for_select(Hash[@contractors.map { |c| [c.contr_name, c.id]}].merge({"нет" => nil}) )%>
    
        <%= f.label "Прикрепить файл" %>
        <%= f.file_field :file %>
  
        <%= f.submit  "Создать", class: 'btn btn-primary btn-lg' %>
        <% end %>
        </div>
</div>


</div>

app/views/documents/show.html.erb
<div class="row">
    <div class="col-auto">
      <%= link_to '« к другим документам', documents_path, class: 'previous', style: 'margin-top:auto' %>
    </div>
</div>



<div class="row">
  <div class="col-sm-4">
  <h1 class="mb-4"><%= @document.name %></h1>
    <div style="opacity: 0.8;">Атрибуты документа</div> 
    <div style="margin:5px 2px 5px; font-weight: 500; font-size: 20px;">Регистрационный номер:
    <span style="font-weight: 300;"><%=@document.number%></span></div>
    <div style="margin:5px 2px 5px; font-weight: 500; font-size: 20px;">Автор документа:
    <%author = User.find_by(id: @document.user_id)%>
    <span style="font-weight: 300;"><%=author.surname%> <%=author.name[0]%>.<%=author.patronymic[0]%>.</span></div>
    <div style="margin:5px 2px 5px; font-weight: 500; font-size: 20px;">Тип документа:
    <span style="font-weight: 300;"><%=@document.doc_type%></span></div>
    <%unless @document.contractor_id.nil?%>
    <div style="margin:5px 2px 5px; font-weight: 500; font-size: 20px;">Контрагент:
    <span style="font-weight: 300;"><%=Contractor.find_by(id: @document.contractor_id).contr_name%></span></div>
    <%end%>
  </div>

  <div class="col-sm-8">
    <iframe src= <%= pdfjs.full_path(file: rails_blob_path(@document.file, disposition: "attachment")) %> width="700" height="600" style="border: none; float:right"> </iframe>
  </div>
</div>



    <%# @routes.each do |route| %>
    <%#= link_to "маршрут #{route.route_name}", document_route_path(@document, route) %> 
    <%#= link_to " удалить #{route.route_name}", document_route_path(@document, route), data: {method: :delete}, style: 'color:#5C2018;' %> 
    <%# end %> 
      <%#= link_to "download #{@document.name}", rails_blob_path(@document.file, disposition: "attachment") %>
      <%if @document.user_id == @current_user.id%>
      <%= link_to 'Удалить документ', document_path(@document), data: {method: :delete, confirm: 'Вы уверены?'}, class: 'previous' %>
      <%end%>
  
 <%#= form_with model: [@document, @route] do |f| %>
<div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
 
    </div>

    <div class="col-sm-10">
      <%#= f.text_field :route_name, class: 'form-control' %>
    </div>
  </div>
  
  <%#= f.submit "Сохранить", class: 'btn btn-primary'%>
<%# end %>
</div>
    
</div>
        
    
     