config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[new create destroy] # в единственном числе, чтобы при DELETE не запрашивался id
  resources :users
  resources :goals, only: %i[new create destroy show] do
    resources :tasks, only: %i[create show destroy]
  end
  resources :handbooks, only: %i[index] 
  get '/departments', to: 'handbooks#departments_link', as: 'departments_link'
  get '/staff', to: 'handbooks#staff_link', as: 'staff_link'


  

  get '/my_documents', to: 'documents#my_documents', as: 'my_documents'

  #get "/routes/:id", to: 'routes#show', as: 'route'  
  get "/goals_inbox", to: 'goals#index_inbox', as: 'inbox_goals' 
  get "/goals_outbox", to: 'goals#index_outbox', as: 'outbox_goals' 

  resources :documents do
    resources :routes, only: %i[new create destroy show]
  end

  resources :routes, only: %i[new create destroy show] do
    resources :steps, only: %i[create show destroy]
  end 
  
  
   
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  root 'pages#index'
end

app/controllers/handbooks_controller.rb
class HandbooksController < ApplicationController
    before_action :require_authentication

    def index
    end

    def staff_link
        @staff = User.where(role:1)
        @departments = Department.all
        render 'handbooks/staff'
    end

    def departments_link
        @departments = Department.all
        @users = User.all
        render 'handbooks/departments' 
    end
end

app/views/handbooks/_menu.html.erb
<div class="row">
<div class="col-sm-3">
<div class="widget">
  <h3>Справочники</h3>
  <ul>
    <li><%= link_to 'Сотрудники', staff_link_path, class: 'a', style:('font-weight:bold;' if current_page?(staff_link_path)) %></li>
    <li><%= link_to 'Отделы', departments_link_path, class: 'a', style:('font-weight:bold;' if current_page?(departments_link_path)) %></li>
    <li><%= link_to 'Маршруты', root_path, class: 'a' %></li>
    <li><%= link_to 'Типы документов', root_path, class: 'a' %></li>
  </ul>
</div>
</div>

app/views/handbooks/departments.html.erb
<%= render 'menu'%>

<div class="col-sm-9">
<table class="book-table">
<caption>Отделы</caption>
  <colgroup>
      <col style="background:#C7DAF0;">
  </colgroup>
  <tr>
    <th>Название</th>
    <th>Руководитель</th>
  </tr>
  <% @departments.each do |department| %>
  <tr>
    <td><%=department.dep_name%></td>
    <td>
     <%if department.user_id.nil? %>
      не указан        
     <%else%>
        <%dep_head = @users.find(department.user_id)%>
        <%= dep_head.surname%> <%= dep_head.name[0]%>.<%= dep_head.patronymic[0]%>.
     <%end%>
    </td>
  </tr>
  <%end%>  
</table>
</div>
</div>

app/views/handbooks/index.html.erb
<%= render 'menu'%>

app/views/handbooks/staff.html.erb
<%= render 'menu'%>

<div class="col-sm-9">
<table class="book-table">
<caption>Сотрудники</caption>
  <colgroup>
      <col style="background:#C7DAF0;">
  </colgroup>
  <tr>
    <th>ФИО</th>
    <th>Телефон</th>
    <th>E-mail</th>
    <th>Должность</th>
    <th>Отдел</th>
    </tr>
  <% @staff.each do |employee| %>
  <tr>
    <td><%= employee.surname%> <%= employee.name%> <%= employee.patronymic%></td>
    <td><%= employee.phone%></td>
    <td><%= employee.email%></td>
    <td><%= employee.post%></td>
    <td>
     <%if employee.department_id.nil? %>
      не указан        
     <%else%>
        <%= @departments.find(employee.department_id).dep_name %>
     <%end%>
    </td>
  </tr>
  <%end%>
</table>
</div>
</div>