config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[new create destroy] # в единственном числе, чтобы при DELETE не запрашивался id
  resources :users
  resources :goals, only: %i[new create destroy show] do
    resources :tasks, only: %i[create show destroy]
  end
  resources :handbooks, only: %i[index] 
  get '/departments', to: 'handbooks#departments_link', as: 'departments_link'
  get '/staff', to: 'handbooks#staff_link', as: 'staff_link'


  

  get '/my_documents', to: 'documents#my_documents', as: 'my_documents'

  #get "/routes/:id", to: 'routes#show', as: 'route'  
  get "/goals_inbox", to: 'goals#index_inbox', as: 'inbox_goals' 
  get "/goals_outbox", to: 'goals#index_outbox', as: 'outbox_goals' 

  resources :documents do
    resources :routes, only: %i[new create destroy show]
  end

  resources :routes, only: %i[new create destroy show] do
    resources :steps, only: %i[create show destroy]
  end 
  
  
   
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  root 'pages#index'
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :delete_all
  has_many :users, through: :tasks
  has_one_attached :file  

  validates :topic, presence: true
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
before_action :require_authentication
before_action :set_goal!, only: %i[edit update show destroy]

include GoalHelper
include StepHelper


    def index_inbox
      #fetch_goals
      #fetch_steps
      @tasks = Task.where user_id: @current_user
      @steps = Step.where(user_id: @current_user, status:"в процессе")
    end

    def index_outbox
      @goals = @current_user.goals.all
    end

    def show
      @task = @goal.tasks.build
      @tasks = Task.where goal_id: @goal.id
      @users = User.all
    end

    def new 
      @goal = Goal.new
    end   
    
    def create
     @goal = @current_user.goals.build goal_params
      if @goal.save
        redirect_to goal_path(@goal)
      else
        flash[:warning] = "Задание НЕ сохранено!"
        redirect_to goals_path
      end
    end

    def edit
    end

    def update
      if @goal.update goal_params
        flash[:success] = "Задание изменено!"
        redirect_to goals_path
      else
        render :edit
      end
    end

    def destroy
      @goal.destroy
      flash[:success] = "Задание удалено!"
      redirect_to goals_path
    end

   

    private
    
    def goal_params
      params.require(:goal).permit(:topic, :start_date, :end_date, :description)
    end

    def set_goal!
      @goal = @current_user.goals.find params[:id]
    end
end

app/helpers/goal_helper.rb
module GoalHelper 

    def fetch_goals
        goals = $redis.get("goals") 
        if goals.nil? 
            goals = Goal.where(topic:"My first goal").to_json 
            $redis.set("goals", goals) 
            $redis.expire("goals",3.hour.to_i) #Кэш обновляется каждые 3 часа
        end 
        @goals = JSON.load goals 
    end 
end 

app/views/goals/index.html.erb
<%#= link_to 'Создать задание', new_goal_path, class: 'btn btn-primary btn-lg mb-3' %>
<div class="col" style="width:50%; float:left;">
<table class="goal-table">
<caption>
    Входящие задания
  </caption>
  <tr> <!--ряд с ячейками заголовков-->
    <th>тема</th>
    <th>от кого</th>
    <th>срок исполнения</th>
    <th>статус</th>
    <th></th>
  </tr> 
  <% @goals.each do |goal| %>
    <tr> <!--ряд с ячейками тела таблицы-->
     <td><%= goal.topic%></td>
     <td><%= goal.user.login%></td>
     <td>18.05.2022 14:00</td>
     <td>Не начато</td>
     <td><%= link_to 'открыть', goal_path(goal), style: 'color:#5C2018;' %></td>
    </tr> 
  <% end %>
 </table>
</div>
<div class="col" style="float:left; padding-left:60px;">
<table class="route-table">
<caption>
    Участие в маршрутах
  </caption>
  <tr> <!--ряд с ячейками заголовков-->
    <th>маршрут</th>
    <th>этап</th>
    <th></th>
  </tr> 
  <% @steps.each do |step| %>
    <tr> <!--ряд с ячейками тела таблицы-->
     <td><%= step.route.route_name%></td>
     <td><%= step.step_type%></td>
     <% route = step.route_id%>
     <td><%= link_to 'открыть', route_step_path(route, step), style: 'color:#5C2018;' %></td>
    </tr> 
  <% end %>
 </table>
</div>

app/views/goals/index_inbox.html.erb
<div class="col" style="width:50%; float:left;">
<table class="goal-table">
<caption>
    Входящие задания
  </caption>
  <tr> <!--ряд с ячейками заголовков-->
    <th>тема</th>
    <th>задание</th>
    <th>от кого</th>
    <th>срок исполнения</th>
    <th>статус</th>
    <th></th>
  </tr> 
  <% @tasks.each do |task| %>
    <tr> <!--ряд с ячейками тела таблицы-->
     <td><%= task.goal.topic%></td>
     <td><%= task.goal.description%></td>
     <%author = User.find_by(id: task.goal.user_id)%>
      <td><%= author.surname%> <%= author.name[0]%>.<%= author.patronymic[0]%>.</td>
     <td>18.05.2022 14:00</td>
     <td>В работе</td>
     <td><%= link_to 'открыть', goal_task_path(task.goal.id, task), style: 'color:#5C2018;' %></td>
    </tr> 
  <% end %>
 </table>
</div>
<div class="col" style="float:left; padding-left:60px;">
<table class="route-table">
<caption>
    Участие в маршрутах
  </caption>
  <tr> <!--ряд с ячейками заголовков-->
    <th>маршрут</th>
    <th>этап</th>
    <th></th>
  </tr> 
  <% @steps.each do |step| %>
    <tr> <!--ряд с ячейками тела таблицы-->
     <td><%#= step.route.route_name%></td>
     <td><%= step.step_type%></td>
     <% #route = step.route_id%>
     <td><%#= link_to 'открыть', route_step_path(route, step), style: 'color:#5C2018;' %></td>
    </tr> 
  <% end %>
 </table>
</div>

app/views/goals/index_outbox.html.erb
<div class="row">
<div class="col-sm-8" style="float:left;">
<table class="goal-table">
<caption>
    Исходящие задания
  </caption>
  <tr> <!--ряд с ячейками заголовков-->
    <th>тема</th>
    <th>дата начала</th>
    <th>срок исполнения</th>
    <th></th>
  </tr> 
  <% @goals.each do |goal| %>
    <tr> <!--ряд с ячейками тела таблицы-->
     <td><%= goal.topic%></td>
     <td><%= goal.start_date%></td>
     <td><%= goal.end_date%></td>
     <td><%= link_to 'открыть', goal_path(goal), style: 'color:#5C2018;' %></td>
    </tr>    
  <% end %>
 </table>
</div>
<div class="col">
<%= link_to 'Создать задание', new_goal_path, class: 'shine-button' %>
</div>
</div>

app/views/goals/new.html.erb
<h1>Новое задание</h1>
<%= form_with model: @goal do |g| %>
  <div class="mb-3 row">
    <div class="col-sm-1 col-form-label">
      <%= g.label :topic, "Тема" %>
    </div>

    <div class="col-sm-5">
  <%= g.text_field :topic, list: 'topic', required: true, class: 'form-control form-control-lg'  %>
  <datalist id="topic">
    <% User.all.each do |user| %>
      <option label="<%= user.login %>"></option>
    <% end %>
  </datalist>  
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-1 col-form-label">
      <%= g.label :description, "Описание" %>
    </div>

    <div class="col-sm-5">
      <%= g.text_field :description, class: 'form-control form-control-lg' %>      
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3 col-form-label">
      <%= g.label :start_date, "Начать" %>
    </div>

    <div class="col-sm-3 col-form-label">
      <%= g.label :end_date, "Закончить" %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-3">
      <%= g.datetime_field :start_date, class: 'form-control form-control-lg' %>
    </div>    

    <div class="col-sm-3">
      <%= g.datetime_field :end_date, class: 'form-control form-control-lg' %>
    </div>  
  </div>
  

  <div class="mb-3 row">
        <%= g.label "Прикрепить файл" %>
        <%= g.file_field :file %>
  </div>
  <%= g.submit "Добавить исполнителей", class: 'button' %>

<% end %>


<%= link_to '<-- назад к списку исходящих', goals_path, style: "color: gray" %>

app/views/goals/show.html.erb
<h1 class="mb-4"><%= @goal.topic %></h1>

  <div class="mb-3 mt-3 row">
   <div class="col-sm-2">
      <h3>Исполнители</h3>
    </div>
  </div>

<% @tasks.each do |task| %>
  <div class="mb-3 row">
    <div class="col-sm-3">
      <%= @users.find(task.user_id).surname%> <%= @users.find(task.user_id).name%>
    </div>

    <div class="col-sm-5">
      <%= task.description %>
    </div>
  </div>
<% end %>

<hr class="my-3">

 <%= form_with model: [@goal, @task] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2">
      <%= f.label :user_id, "Выберите сотрудника: "%> 
    </div>

    <div class="col-sm-5">
      <%= f.text_field :user_id, list: 'user', class: 'form-control form-control-lg', onclick: "upperCase();"  %>
      <datalist id="user">
        <% User.all.each do |user| %>
          <option label="<%=user.surname%> <%=user.name[0]%>.<%=user.patronymic[0]%>." value ="<%= user.id %>"></option>
        <% end %>
      </datalist>    
    </div>
  </div>

     <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <p>Дополнительное описание задания сотрудника</p>
    </div>

    <div class="col-sm-5">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>
<div class="col-sm-6">
  <%= f.submit "Добавить", class: 'button'%>  </div>
<% end %>